### ISSUE TITLE
Homework #1 completed

### ISSUE THREAD

**Issue by SofyaMulenok** [SofyaMulenok/homework_week1#2]
@DiyahM @Keenahn @LijieZhou

Homework number 1 completed, see the details in repo README.md file.

**Comment by LijieZhou** [comment]
Hi @Sofya I'm so happy to see your website! Great job! It looks professional!

I have one suggestion for you: you have used several images and usually we have a separate folder for the image files. Simply create a folder called "img" and drop all the images there. You need to change the image source after making this change, but I believe you will figure out. Congratulations on all the CSS work. It's great you have some experience before our CSS class this week. Do you use it at work or you just figured out? Either way is great you made it. Usually we have a separate CSS file, instead of mixing it with HTML. Don't worry. You will learnt it tonight. 

Look forward to seeing you tonight! 

Lijie

**Comment by SofyaMulenok** [comment]
Thank you very much for the useful feedback, Lijie!
I don't use very much of css at work, but I have tried learning it multiple times by myself.
I will keep my eyes wide open for today's class :)

Thanks again,
Sofya
